<?php if ($this->allow) {?>
<div align="right"><?php echo $this->subButtons?></div>

<hr>

<table id="dtb_comments" class="dTable table table-hover table-bordered table-condensed table-mini">
	<thead>
		<tr>
			<th>Student no.</th>
			<th>Fullname</th>
			<th width="100">Comment</th>
			<th width="100">Base</th>
			<th width="100">Mark</th>
			<th width="100">Exempt</th>
			<th width="35" align="center">%</th>
		</tr>
	</thead>
	<tbody>
    </tbody>
</table>

<div class="btn-group" data-toggle="buttons-radio">
<?php
  foreach ($this->classes as $key => $value) {
      $n = $this->getGradeName($value);
      echo "<button id='bb$key' class='btn btn-danger btn-small' type='button' onclick='$.fn.filterComments($(\"#c\").text(),$value)'>$n</button>";
  }
?>
</div>

<div align="left"><?php echo $this->subButtonsClasses?></div>

<script type="text/javascript">
<!--
$(function (){
	var dtb_comments = $('#dtb_comments').dataTable( {
		"sDom": "<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'pl>>",
		"sPaginationType": "bootstrap",
	    "iDisplayLength" : 20,
		"bAutoWidth": false,

		"bProcessing": true,
		"bStateSave": false,
		"bServerSide": true,
		//"sServerMethod": "GET",
		"sAjaxSource": "/commentsource",
		"fnServerData": function ( sSource, aoData, fnCallback, oSettings ) {
			  aoData.push( { "name": "cid", "value": "<?php echo $this->firstcourse; ?>" } );
			  aoData.push( { "name": "grade", "value": "<?php echo $this->classes[0];?>" } );
		      oSettings.jqXHR = $.ajax( {
		        "dataType": 'json',
		        "type": "POST",
		        "url": sSource,
		        "data": aoData,
		        "success": fnCallback
		      });
		      },
		"aaSorting": [],
	    "sScrollY": "250px",
	    "bScrollInfinite": true,
	    "bScrollCollapse": true,
	    "bPaginate": true,

		"oLanguage" : {
			 "sProcessing": "<img src='/img/loaders/cloader2.gif'> Server processing request...",
			 "sEmptyTable": "You have not been assigned the selected subject and selected class",
		    },

		"aoColumnDefs": [    /*{"bSortable":false, "aTargets":[2,3,4,5]},
			                   { "bVisible": false, "aTargets": [ 0 ] },
		                       { "sClass": "markbase", "aTargets": [ 2 ] },
			                   { "sClass": "markrow", "aTargets": [ 3 ] },
			                   { "sClass": "exemptrow", "aTargets": [ 4 ] },*/
			             ],
		"fnDrawCallback": function( oSettings ) {
							 $("a[rel=popover]")
				 		     .popover()
				 		     .click(function(e) {
				 		       e.preventDefault();
				 		     });
				   		  },

		"fnRowCallback": function( nRow, aData, iDisplayIndex ) {
		 			            var id = aData[0];
		 			            	$(nRow).attr("id",id);
		 		},

		"fnInfoCallback": function( oSettings, iStart, iEnd, iMax, iTotal, sPre ) {
		 		    return "Showing " + iStart+ " to "+ iEnd + " of "+ iTotal + " entries";

		 		},
		"oTableTools": {
			//"sRowSelect": "single",
			"sSwfPath": "/js/tabletools/swf/copy_csv_xls_pdf.swf",
			"aButtons": [
							"copy",
							"print",
							"xls",
							"pdf",
							{
			                    "sExtends":    "text",
			                    "sButtonText" : "Refresh Data",
			                    "sButtonClass" : "btn-success whitetext",
			                    "fnClick": function ( nButton, oConfig, oFlash ) {
			                    	dtb_comments.fnReloadAjax();
			                    }
			                }],


			"fnRowSelected": function (node){
			}
		}
	});

    $.fn.filterComments = function(course, grade){
        $('#c').text(course);
        $('#g').text(grade);
        dtb_comments.fnReloadAjax( '/commentsource?cid=' + course + '&grade=' + grade );
    };
    //end of filterassignments

	$.fn.loadComments = function (examsid, title, std){
		<?php if($this->current) { ?>
		$.loadModal('/loadcomment?studentid='+std,title,examsid);
		 <?php } else { ?>
		 	bootbox.alert('Access Denied (Code 101) : Contact Administrator');
		 <?php } ?>
	};

	$.fn.updateComment = function (examid, sid, cm){
		<?php if($this->current) { ?>
		bootbox.confirm('Are you sure you want to save updated comments?', function(response){
			if(response){
				$.post('/updatecomment',
						{
						eid : examid,
						cm : cm,
						course : $('#c').text(),
						grade : $('#g').text(),
						studentid : sid
						},
						function(){
							$('#dtb_comments').block();
							dtb_comments.fnReloadAjax();
							$('#dtb_comments').unblock();
				});
			}
		});
		 <?php } else { ?>
		 	bootbox.alert('Access Denied (Code 101) : Contact Administrator');
		 <?php } ?>
	};

	$(".table").not('#astats').tablecloth({ theme: "paper" });
	$('#btnfirst').button('toggle');
	$('#bb0').button('toggle');

});
</script>
<?php } else { echo $this->action('noauth', 'error', 'security'); }?>