
<div class="tabbable tabs-above">
	<ul id="myTab" class="nav nav-pills">
            <li class="active"><a href="#listinstructors" data-toggle="tab">List of Instructors</a></li>
            <li><a href="#allassigns" data-toggle="tab">Instructor Assignments</a></li>
		<!--<li><a href="#editinstructor" data-toggle="tab">Edit Instructor</a></li> -->
	</ul>

	<div id="myTabContent" class="tab-content" style="min-height: 450px;">
		<div class="tab-pane fade in active" id="listinstructors">
			<p>

			</p>
		</div>
	</div>
</div>



<!-- SCRIPT SECTION -->
<script type="text/javascript">

      $(function(){
    	    $('a[href="#listinstructors"]').on('click', function (e) {
    	        $.post(
    	        	    '/listinstructors',
    	        	    {
    	        	    },
    	        	    function (data){
    	        	        $('#listinstructors').html(data);
    	        	    });
    	    });

    	    $('a[href="#allassigns"]').on('click', function (e) {
    	        $.post(
    	        	    '/instructor/allsubjects-assigned',
    	        	    {
    	        	    },
    	        	    function (data){
    	        	        $('#listinstructors').html(data);
    	        	    });
    	    });


    	  //make ajax call to list of instructors
    	  $('a[href="#listinstructors"]').click();

  	      $('#cl_inst_id').val('');

     });
</script>