 
<table id="dtb_sheet" class="table table-mini table-condensed table-bordered table-hover table-stripped">
<thead>
	<tr>
		<th width="250">Student Name</th>
		<th width="100" align="center"><?php echo $this->weekdays[0]?></th>
		<th width="100" align="center"><?php echo $this->weekdays[1]?></th>
		<th width="100" align="center"><?php echo $this->weekdays[2]?></th>
		<th width="100" align="center"><?php echo $this->weekdays[3]?></th>
		<th width="100" align="center"><?php echo $this->weekdays[4]?></th>
    	<th width='100' align="center">Total</th>
	</tr>
</thead>	
  <tbody>
    
	<?php foreach ($this->attendanceSheet as $sheet) {  $total = 0;?>
		  <tr>
		  		<td width="250"><?php echo $sheet->student?></td>
		  		<?php if($sheet->lateness[0] != -1) { $total += $sheet->lateness[0] ?>
					<td width='100' align="center" style="font-weight: bold;color:blue"><?php echo ($sheet->lateness[0] != 0) ?  $sheet->lateness[0] :  "<span style='color:green; font-weight:bold'>ONT</span>";?></td>
				<?php } else { ?>
					<td width='100' align="center" style="color:maroon; font-weight: bold;">ABS</td>
				<?php } ?>
				
				<?php if($sheet->lateness[1] != -1) { $total += $sheet->lateness[1]?>
					<td width='100' align="center" style="font-weight: bold;color:blue"><?php echo ($sheet->lateness[1] != 0) ?  $sheet->lateness[1] :  "<span style='color:green; font-weight:bold'>ONT</span>";?></td>
				<?php } else { ?>
					<td width='100' align="center" style="color:maroon; font-weight: bold;">ABS</td>
				<?php } ?>
				
				<?php if($sheet->lateness[2] != -1) { $total += $sheet->lateness[2]?>
					<td width='100' align="center" style="font-weight: bold;color:blue"><?php echo ($sheet->lateness[2] != 0) ?  $sheet->lateness[2] :  "<span style='color:green; font-weight:bold'>ONT</span>";?></td>
				<?php } else { ?>
					<td width='100' align="center" style="color:maroon; font-weight: bold;">ABS</td>
				<?php } ?>
				
				<?php if($sheet->lateness[3] != -1) { $total += $sheet->lateness[3]?>
					<td width='100' align="center" style="font-weight: bold;color:blue"><?php echo ($sheet->lateness[3] != 0) ?  $sheet->lateness[3] :  "<span style='color:green; font-weight:bold'>ONT</span>";?></td>
				<?php } else { ?>
					<td width='100' align="center" style="color:maroon; font-weight: bold;">ABS</td>
				<?php } ?>
				
				<?php if($sheet->lateness[4] != -1) { $total += $sheet->lateness[4]?>
					<td width='100' align="center" style="font-weight: bold;color:blue"><?php echo ($sheet->lateness[4] != 0) ?  $sheet->lateness[4] :  "<span style='color:green; font-weight:bold'>ONT</span>";?></td>
				<?php } else { ?>
					<td width='100' align="center" style="color:maroon; font-weight: bold;">ABS</td>
				<?php } ?>
				
				<td width='100' align="center" style="color: black; font-weight: bold;"><?php echo ($total != 0) ? $total.' mins' : '-' ;?></td>
			</tr>
	<?php } ?></tbody>
</table>
 
<script type="text/javascript">
<!--

	var dtb_sheet = $('#dtb_sheet').dataTable( {
		"sDom": "<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'pl>>",
		"sPaginationType": "bootstrap",
	    "iDisplayLength" : 10,
		"bAutoWidth": false,

		"bProcessing": true,
		"bStateSave": false,

		"aaSorting": [[ 6, "desc" ]],
	    //"sScrollY": "250px",
	    "bPaginate": true,

		"oLanguage" : {
			 "sUrl" : "/js/locale/datatables.english.txt"
		    },

 
		"oTableTools": {
			//"sRowSelect": "single",
			"sSwfPath": "/js/tabletools/swf/copy_csv_xls_pdf.swf",
			"aButtons": [
							"copy",
							"print",
							"xls",
							"pdf",
							],
			"fnRowSelected": function ( node ) {

			}
		}
	});


$(".table").not('#astats').tablecloth({ theme: "paper" });
$('#ajax-modal').width(1000);
$('#ajax-modal').css('left','28%');


//-->
</script>