<div class="tabbable tabs-above">
	<ul id="myTab" class="nav nav-pills">
            <li class="active"><a href="#listcurrentstudents" data-toggle="tab">Current Students</a></li>
            <li><a href="#listpaststudents" data-toggle="tab">Past Students</a></li>
            <li><a href="#listoldstudents" data-toggle="tab">Old Students(Graduates)</a></li>
	</ul>

	<div id="myTabContent" class="tab-content" style="min-height: 480px;">
		<div class="tab-pane fade in active" id="listcurrentstudents"></div>
		<div class="tab-pane fade in active" id="listpaststudents"></div>
		<div class="tab-pane fade in active" id="listoldstudents"></div>
	</div>
</div>

<!-- SCRIPT SECTION -->
<script type="text/javascript">
      $(function(){
    	    $('a[href="#listcurrentstudents"]').on('click', function (e) {
    	        $.post(
    	        	    '/student/listcurrentstudents',
    	        	    {
        	        	    locked : true
    	        	    },
    	        	    function (data){
    	        	        $('#listcurrentstudents').html(data);
    	        	    });
    	    });


    	    $('a[href="#listpaststudents"]').on('click', function (e) {
    	        $.post(
    	        	    '/student/listpaststudents',
    	        	    {
        	        	    locked : true
						},
    	        	    function (data){
    	        	        $('#listpaststudents').html(data);
    	        	    });
    	    });


    	    $('a[href="#listoldstudents"]').on('click', function (e) {
    	        $.post(
    	        	    '/student/listoldstudents',
    	        	    {
        	        	    locked : true
        	        	},
    	        	    function (data){
    	        	        $('#listoldstudents').html(data);
    	        	    });
    	    });


    	  $.fn.toggleStudentStatus = function (studentid, page){
    	  <?php if(!$this->locked){ ?>
    	  
  		      var msg = '';
  		      var btn = '';

  		    if (page == 0){
  	  		    msg = 'Sure you want to withdraw selected student?';
  	  		    btn = 'Withdraw student';
  		    }
  		    else{
  	  		    msg = 'Sure you want to re-admit selected student?';
  	  	  		btn = 'Re-admit student';
  		    }

  		      bootbox.confirm(msg,'Cancel',btn,
  		  		  function (result){
    		        if (result){
    		        	$.post(
    		      			    '/student/toggle-status',
    		      			    {
    		          			    studentid : studentid
    		          			},
    		          			function (data){
    		          			    if (page == 0)
    		          			    	$('a[href="#listcurrentstudents"]').click();
    		          			    else
    		          			    	$('a[href="#listpaststudents"]').click();
    		          			}
    		          	);
    		        }
	  		      });
              <?php } else { ?>
				bootbox.alert('Access denied.')
        <?php } ?>
     	  };
     	  

    	  $.fn.updateStudentRecord = function (studentid){
			<?php if(!$this->locked){ ?>
    		  $.post('/studentrecord',
                    	{
                           send : false,
                           studentid : studentid,
                           update : true,
                    	},
                    	function (data){
                    	    $('#listcurrentstudents').html(data);
                    	});
            <?php } else { ?>
				bootbox.alert('Access denied')
            <?php } ?>
    	  };


  	      $.fn.studentPreview = function (studentid){
  	  	      $.showMessage('load student data preview');
  	      };


    	  //make ajax call to list of instructors
    	  $('a[href="#listcurrentstudents"]').click();
     });
</script>