<tr  id="<?php echo $this->cl_IID; ?>">
<td><?php echo $this->cl_IID; ?></td>
<td><?php echo $this->firstname .' '.$this->lastname  ;  ?> - <span class="label label-mini"><?php echo ($this->getRoleName($this->role)) ?></span></td>
<td><span style="font-size: 12px;"><?php echo $this->getGradeName($this->cl_classteacher); ?></span> </td>

<td>
<?php if($this->active) { ?>
			<span class="label label-important label-mini"><a href="/instructor/deactivate/instructor/<?php echo $this->cl_IID; ?>">deactivate</a></span>
	<?php }   else { ?>
			<span class="label label-success label-mini"><a href="/instructor/activate/instructor/<?php echo $this->cl_IID; ?>">activate</a></span>
	<?php	   }?>

	<span class="label label-info label-mini"><a href="" onclick="$.fn.getInstDetails(<?php echo $this->cl_IID; ?>,'<?php echo $this->firstname.' '.$this->lastname;?>'); return false;">edit</a></span>
    <span class="label label-inverse label-mini"><a href="" onclick="$.fn.resetPassword(<?php echo $this->cl_IID; ?>, '<?php echo $this->firstname.' '.$this->lastname;?>'); return false;" title="Reset Instructors Password">reset pwd</a></span>
</td>
<td> <?php echo $this->email; ?></td>
<td> <?php echo $this->telno; ?></td>
<td> <?php echo $this->ecode; ?></td>
</tr>