<?php if( $this->locked) {  ?>
    <div class="alert alert-error"><strong>LOCKED RECORDS</strong> : These records have been marked as read-only; </div>
<?php } ?>
        <div id="salert"></div>
        <table class="table table-bordered table-striped table-condensed">
        <thead>
             <tr>
                 <th align="right">Academic Year</th><th><span id="year" class='label label-inverse'><?php echo $this->year; ?></span></th>
                 <th align="right">Term</th><th><span id="term" class='label label-inverse'><?php echo $this->term; ?></span></th>
                 <th align="right">Subject</th><th><span class='label label-inverse'><?php echo $this->coursename; ?></span> </th>
                  <th align="right">Grade</th><th><span id="gc" class='label label-inverse'><?php echo $this->gradename; ?></span></th>
                 <th align="right">Max. Mark</th><th><span id="lbl_maxmarkinfo" class='label label-inverse'><?php echo $this->maxmark; ?></span></th>
                 <th align="right">AID</th><th><span id="assigninfo" class='label label-success'><?php echo $this->assignmentid; ?></span></th>
              </tr>
           </thead>
         </table>

		<table id="dtb_assessmentmarks" class="table table-bordered table-hover table-condensed" style="font-size: 12px;">
			<thead>
				<tr>
					<th width = 30>AID</th>
					<th width = 100>Student No</th>
					<th>Fullname</th>
					<th width = 150 >Mark</th>
					<th width = 100 > Exempted </th>
				</tr>
			</thead>
			 <tbody>
            <?php
        	        $list1 = array();
        	        $list2 = array();

    	    	foreach ($this->studentsInGrade as $key => $student) {
     				$list1[$student["cl_GPSN_ID"]] = trim($student["fullname"]);
           		}

           		foreach ($this->scoreslist as $key => $assignmentmark) {
           			$list2[$assignmentmark->cl_studentid] = trim($assignmentmark->cl_LastName);
           		}

           		$newStudents = array();
           		
           		if(!$this->archived)
           		  $newStudents = array_diff_key($list1, $list2);

           		foreach ($newStudents as $key => $value) { ?>
           			       	    	 <tr id="<?php echo $key ?>">
           								<td id="assign_id"><?php echo $this->cl_assignmentid ?></td>
           								<td><?php echo $key ?></td>
           								<td><strong style="color : red"><?php echo $value ?></strong><i> *n</i></td>
           								<td class="markrow">0</td>
           								<td class="exemptrow">
           								   <?php if ($this->cl_exempt)
           											echo 'Yes';
           										else
           											echo 'No'; ?>
           								</td>
           							</tr>
           		       	   <?php  }	?>
             <?php  echo $this->partialLoop('partials/_mark-scores-row.phtml', $this->scoreslist); ?>

             </tbody>
		</table>
		       	<?php if (count($newStudents) > 0) {
		       	    $newStudents = array_values($newStudents);
		       	    ?>
           	   		<script type="text/javascript">
              	     $('#salert').html("<div class='alert alert-block alert-info fade in'><button type='button' class='close' data-dismiss='alert'>&times;</button><p><strong>System Alert!  </strong> Post assessment enrollments : <span class='label label-important'><?php echo implode('</span> | <span class=\'label label-important\'>', $newStudents); ?></span></p></div>");
           	   		</script>
       	   <?php } ?>
<?php ?>

<script type="text/javascript">
<!--
$(function(){
	var dtb_assessmentmarks = $('#dtb_assessmentmarks').dataTable( {
		"sDom": "<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'pl>>",
		"sPaginationType": "bootstrap",
	    "iDisplayLength" : 10,
		"bAutoWidth": false,

		"bProcessing": true,
		"bStateSave": false,

		"aaSorting": [],
	    //"sScrollY": "250px",
	    "bPaginate": true,

		"oLanguage" : {
			 "sUrl" : "/js/locale/datatables.english.txt"
		    },

		"aoColumnDefs": [
			                 //{ "bSortable": false, "aTargets": [ 2 ] }
			             ],

		"oTableTools": {
			//"sRowSelect": "single",
			"sSwfPath": "/js/tabletools/swf/copy_csv_xls_pdf.swf",
			"aButtons": [
							"copy",
							"print",
							"xls",
							"pdf",
							],
			"fnRowSelected": function ( node ) {

			}
		}
	});

	<?php if( !$this->locked) {  //disabling editing of marks of archived data?>
		
	if ($('#dtb_assessmentmarks').length  > 0) {

				 //Apply the jEditable handlers to the table
		dtb_assessmentmarks.$('td.markrow').editable( '/postassessmarks',
					{
					"callback": function( sValue, y ) {
						if (sValue != 'Invalid mark'){
							//$.showMessage('Update successful');
						}
						else{
							bootbox.alert('Aborted: Mark is outside the range 0 - ' +  $('#lbl_maxmarkinfo').text() );
						}
					},
					"submitdata": function ( value, settings ) {
						return {
							"maxmark" : $('#lbl_maxmarkinfo').text(),
							"assignment_id" : $('#assigninfo').text(),
							"student_id": this.parentNode.getAttribute('id'),
							"column": dtb_assessmentmarks.fnGetPosition( this )[2]
						};
					},
					type : "masked",
					mask : "?999",
					placeholder: "click to add mark",
					onblur : "submit",
					height: "15px",
					width : "50%",
				    event : "click"
			});


		dtb_assessmentmarks.$('td.exemptrow').editable( '/postassessexempt',
					{
					"callback": function( sValue, y ) {
							//$.showMessage('Update successful');
					},
					"submitdata": function ( value, settings ) {
						return {
							"maxmark" : $('#lbl_maxmarkinfo').text(),
							"assignment_id" : $('#assigninfo').text(),
							"student_id": this.parentNode.getAttribute('id'),
							"column": dtb_assessmentmarks.fnGetPosition( this )[2]
						};
					},
					type: 'select',
					data : {0:"No" , 1:"Yes"},
					onblur : "submit",
					height: "25px",
					width : "50px",
				    event : "dblclick"
			});
	}
	<?php  } ?>
//		dtb_assessmentmarks.fnSetColumnVis(0, false);
//
	$('#ajax-modal').width(900);
	$('#ajax-modal').css('left','38%');
	//$('#ajax-modal').css('margin-top','0px !important');
	$(".table").not('#astats').tablecloth({ theme: "paper" });
});
//-->
</script>
  