<div class="span8 row-fluid">
	<div class="span12 alert alert-block alert-white fade in"
		style="margin-left: 0px;">
		<table class="table table-hover table-striped table-bordered">
			<thead>
				<tr>
					<th colspan="2">Classes and Subjects Info <small style="color: green;">(Hovering on subjects shows their complete names)</small> </th>
				</tr>
				<tr>
					<th width="200">Item</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Assigned Classes</td>
					<td><?php echo $this->getGradeListRaw($this->assignedClasses);?></td>
				</tr>
				<tr>
					<td>Assigned Subjects</td>
					<td><?php echo $this->assignedSubs;?></td>
				</tr>

				<tr>
					<td>Total number of students</td>
					<td><?php echo $this->totalStudents;?>
					<?php if ($this->lock == NULL) {?>
						<button id="newassess" class="btn btn-danger btn-small pull-right" onclick="$.fn.newAssessment();">New Assessment <i class="icon-white icon-plus-sign"></i></button>
					<?php } ?>
					</td>
				</tr>

			</tbody>
		</table>

		<table class="table table-hover table-striped table-bordered table-condensed">
			<thead>
				<tr>
					<th colspan="2">Assessments Summary and Monitoring</th>
				</tr>
			</thead>
			<tbody>
				 <tr>
					<td width="300">Total no. of assessments / * students</td>
					<td><span class='label label-inverse'><?php echo $this->totalAssess; ?> / <?php echo $this->totalStdAss;?></span></td>
				</tr>
				 <tr>
					<td width="200"><a>Graded students assessments</a></td>
					<td><span class='label label-success'><?php echo $this->totalGraded; ?></span></td>
				</tr>
				<tr>
					<td width="200"><a href="#" onclick="$('#ug').click(); return false;">Ungraded students assessments</a></td>
					<td><span class='label label-important'><?php echo $this->totalUnGraded;  ?></span></td>
				</tr>
				<tr>
					<td width="200"><a href="#" onclick="$('#zg').click(); return false;">Zero graded student assessments</a></td>
					<td><span class='label label-important'><?php echo $this->totalZero; ?></span></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div class="span4 alert alert-block alert-info fade in">
	<button type="button" class="close" data-dismiss="alert"></button>
	<h5 class="alert-heading">Assessment Statistics</h5>
	 <table  id="astats" class="table table-condensed table-hover table-mini" >
	     <tr>
    	     <th><span class='label label-inverse label-mini'>Subject</span></th>
    	     <th><span class='label label-inverse label-mini'>Class</span></th>
    	     <th><span class='label label-inverse label-mini'>Total</span></th>
    	 </tr>
             <?php
              $sum = 0;
              foreach ($this->stats as $stat) {
                  $g = $this->getGradeName($stat->cl_grade);
                  $st = substr($stat->subject, 0, 10);
                  $sum += $stat->cnt;
                  echo "<tr><td>$st</td><td>$g</td><td style='text-indent : 10px;'>$stat->cnt</td></tr>";
              }
             ?>
          <tr><td colspan="2"><span class='label label-important label-mini'>Total # of assessments</span></td><td><span class='label label-important label-mini'><?php echo $sum; ?></span></td></tr>
     </table>
</div>

<!-- SCRIPTS SECTION -->
<script type="text/javascript">
<!--
$(function (){ //document ready function call

	<?php if ($this->totalUnGraded > 0) {?>
        $('#ul').html('<span class="label label-inverse label-mini" style="padding : 0px 2px;"><?php echo $this->totalUnGraded;  ?></span>');
    <?php } ?>

	<?php if ($this->totalZero > 0) {?>
    	$('#zl').html('<span class="label label-inverse label-mini"  style="padding : 0px 2px;"><?php echo $this->totalZero;  ?></span>');
    <?php } ?>

	<?php if ($this->totalZero > 0) {?>
		$('#el').html('<span class="label label-inverse label-mini"  style="padding : 0px 2px;"><?php echo $this->totalExempt;  ?></span>');
	<?php } ?>

	$(".table").not('#astats').tablecloth({ theme: "paper" });
	$("a[rel=tooltip]").tooltip({placement : "bottom"});


});
//-->
</script>