 <?php
    // setting the controller and action name as title segments:

    $this->headTitle('Assignment - List')
    	 ->headTitle('MVC Application');

    // setting a separator string for segments:
    $this->headTitle()->setSeparator(' - ');

	//LOADING OF VIEW SPECIFIC JAVASCRIPT FILES
  ?>
   <?php
		if ($this->assignments != null) {
	?>
	  <div class="widget">
	  <div class="title"><img src="/images/icons/dark/timer.png" alt="" class="titleIcon" /><h6>Assignment Marks Entry Section</h6><div class="num"><a href="" class="blueNum">Edit</a></div></div>
			    <div style="max-height: 250px; overflow: auto;" >
					  <table cellpadding="0" cellspacing="0" width="100%" class="sTable taskWidget">
							 <thead>
							  <tr>
							   <td >Assignment List</td>
							   <td >Ac. Year</td>
							  </tr>
							 </thead>
							<tbody>
							    <?php  echo $this->partialLoop('partials/_assignments-row.phtml',  $this->assignments); ?>
							</tbody>
					 </table>
			 </div>
	 	</div>

	 <div class="widget" style="margin-top: 20px;" id="assign-details">
				<div class="title">
					<img src="/images/icons/dark/preview.png" alt="" class="titleIcon" />
					<h6>Assignment Details</h6>
					 	<div class="num"><a id="markurl" class="greyNum">Enter student's marks</a></div>
					 	<div class="num"><a id="markurl" class="redNum">Delete Assignment</a></div>
					<div class="topIcons">
						<a href="#" class="tipS" title="Download statement"><img
							src="" alt="" /></a> <a href="#"
							class="tipS" title="Print invoice"><img
							src="" alt="" /></a> <a href="#"
							class="tipS" title="Edit"><img src=""
							alt="" /></a>
					</div>
				</div>
				<div class="newOrder">
					<div class="userRow">
						<a href="#" title=""><img src="/images/icons/sticky.png" alt=""
							class="floatL" /></a>
						<ul class="leftList" style="margin-top: 5px;">
							<li><a href="#" title=""> Course Name </a></li>
							<li>Assignment Topic</li>
						</ul>
						<ul class="rightList" style="margin-top: 5px;">
							<li><a href="#" title="" > <strong id="lbl_coursename"> .</strong></a></li>
							<li class="orderIcons"><span class="oFinished"
								style="margin-top: 5px;"></span><label id="lbl_topic">.</label></li>
						</ul>
						<div class="clear"></div>
					</div>

					<div class="cLine"></div>

					<div class="orderRow">
						<ul class="leftList">
							<li>Date Assigned</li>
							<li>Date Dued</li>
							<li>Maximum Mark</li>
							<li>Highest Mark</li>
							<li>Lowest Mark</li>
							<li>Type of Assignment</li>
						</ul>
						<ul class="rightList">
							<li><strong id="lbl_date"> . </strong></li>
							<li><strong id="lbl_datedued" class="green">. </strong></li>
							<li><strong id="lbl_maxmark" class="orange"> . </strong></li>
							<li><strong class="orange"> .</strong></li>
							<li><strong class="orange"> .</strong></li>
							<li><strong id="lbl_type" class="orange">. </strong></li>
						</ul>
						<div class="clear"></div>
					</div>

					<div class="cLine"></div>
					<div class="totalAmount">
						<h6 class="floatL blue">.</h6>
						<h6 class="floatR blue">.</h6>
						<div class="clear"></div>
					</div>
				</div>
			</div>

    <?php } else {?>
     <p style="padding: 20px; text-align: center;">You do not have access to any assignments. Either you haven't added any assignments or access is denied to assignments</p>
   <?php }?>
