<div class="pcss3rm pcss3rm-pos-br">
	<input type="checkbox"> <a href="#" class="color-red hcolor-white"> <i class="color-white hcolor-orange icon-home"></i>
	</a>
	<ul>
		<li><a href="/managestudents?newstudent=1" class="hcolor-blue"> <i class="color-blue hcolor-white icon-user"></i>
		</a> <em class="bl">Enrol New Student</em></li>
		<li><a href="#" class="hcolor-cyan"> <i class="color-cyan hcolor-white icon-twitter"></i>
		</a> <em class="bl">Twitter</em></li>
		<li><a href="#" class="hcolor-red"> <i class="color-red hcolor-white icon-pinterest"></i>
		</a> <em class="bl">Pinterest</em></li>
		<li><a href="#" class="hcolor-green"> <i class="color-green hcolor-white icon-google-plus"></i>
		</a> <em class="bl">Google Plus</em></li>
		<li><a href="/logout" class="hcolor-red"> <i class="color-pink hcolor-white fa fa-lock"></i>
		</a> <em class="bl">Logout</em></li>
	</ul>
</div>