
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<link rel="stylesheet" href="/css/print_alternate.css"></link>
</head>
<body>
<!--mpdf
<htmlpageheader name="myheader">
<span style="font-size: 9pt;">Compilation of subjects teachers' remarks on <?php echo $this->studentname?></span>
<div style="border-top: 1px solid #000000; font-size: 9pt; text-align: center; padding-top: 3mm; "></div>
</htmlpageheader>

<htmlpagefooter name="myfooter">
<div style="border-top: 1px solid #000000; font-size: 9pt; text-align: center; padding-top: 3mm; ">
<table width="100%">
<tr>
	<td width="32%" style=" font-size: 9pt; border:none;">Page {PAGENO} of {nb}</td>
	<td width="32%" style=" font-size: 9pt; border:none;"><?php echo $this->studentname?></td>
	<td width="32%" style=" font-size: 9pt; text-align: right;  border:none;">Term <?php echo $this->term?> of <?php echo $this->year ?></span></td>
</tr>
</table>
</div>
</htmlpagefooter>

<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
<sethtmlpagefooter name="myfooter" value="on" />
mpdf-->
	   <table  cellpadding="0" cellspacing="0" style=" width: 100%; border: 0px;" class="table-dotted">
	     <tr >
	       <td class="commentcell bleft">NAME OF STUDENT</td><td class="commentcell"><strong>
    					<?php if(isset($this->studentname))
					 	     echo strtoupper($this->studentname); ?></strong></td>
	     </tr>
	   </table>
	 	 <?php echo $this->partialLoop('partials/_comment-report-row.phtml', $this->comreport) ?>
	    <div style="height: 10px;">   </div>
	   	 <div style="page-break-inside: avoid; ">
                          		<table cellpadding="0" cellspacing="0" style=" width: 100%; ">
                          		  <tr style="height: 100px;">
                          		   <td style="width: 170px; vertical-align: middle; text-align: center; border: 1px solid #4F81BD; border-bottom:1px; border-right:1px;" ><span style="color: white;">.</span><br>Class Teacher's Remark<span style="color: white;">.</span></td>
                          		   <td  style="border: 1px solid #4F81BD; border-bottom:1px;  vertical-align: middle; font-size: 12px; padding-top: 10px; padding-bottom: 10px; "> <?php echo $this->ctcomment; ?></td></tr>
                          		  <tr style=" height: 30px;">
                          		  <td style="width: 150px; vertical-align: middle; text-align: center; border: 1px solid #4F81BD; border-right:1px;"><span style="color: white;">.</span><br>Signature</td>
                          		  <td  style="vertical-align: middle; text-align: center; border: 1px solid #4F81BD; font-weight: bold;"></td></tr>
                          		</table>

                          		<table cellpadding="0" cellspacing="0" style=" width: 100%; margin-top: 20px;">
                          		  <tr style="height: 70px;">
                          		   <td style="width: 170px; vertical-align: middle; text-align: center; border: 1px solid #4F81BD; border-bottom:1px; border-right:1px;" ><br>Head of School's Remark<br><span style="color: white;">.</span></td>
                          		   <td  style="border: 1px solid #4F81BD; border-bottom:1px; font-size: 12px; vertical-align: middle; padding-top: 10px; padding-bottom: 10px; "><?php echo $this->prcomment; ?> </td></tr>
                          		  <tr style=" height: 30px;">
                          		  <td style="width: 150px; vertical-align: middle; text-align: center; border: 1px solid #4F81BD; border-right:1px;"><span style="color: white;">.</span><br>Signature</td>
                          		  <td  style="vertical-align: middle; text-align: center;  border: 1px solid #4F81BD; font-weight: bold;"></td></tr>
                          		</table>
         </div>
</body>
</html>

