<?php
//REPORT TYPES
DEFINE("REPORT_TYPE_DAILY",1);

//REPORT QUERY TYPES
DEFINE ("QUERY_TYPE_STANDARD",1);
DEFINE ("QUERY_TYPE_MIN",2);
DEFINE ("QUERY_TYPE_MAX",3);
DEFINE ("QUERY_TYPE_TOTALWASTE",4);
DEFINE ("QUERY_TYPE_THERMALPOWER",5);
DEFINE ("QUERY_TYPE_LHV",6);
DEFINE ("QUERY_TYPE_WASTETHROUGHPUT",7);
DEFINE ("QUERY_TYPE_AVAILABILITY95",8);
DEFINE ("QUERY_TYPE_TOTALCONSUMPTION",9);
DEFINE ("QUERY_TYPE_EQUATION",10);
DEFINE ("QUERY_TYPE_LASTVALUE",11);

//SIGNAL TYPES
DEFINE ("SIGNAL_TYPE_ALL",-1);
DEFINE ("SIGNAL_TYPE_MEASUREMENT",1);
DEFINE ("SIGNAL_TYPE_CONSTANT",2);
DEFINE ("SIGNAL_TYPE_EQUATION",3);

//LOADPOINTS
DEFINE ("LP1",1);
DEFINE ("LP2",2);
DEFINE ("LP3",3);
DEFINE ("LP4",4);
DEFINE ("LP5",5);
DEFINE ("LP6",6);

DEFINE ("LP1o",11);
DEFINE ("LP2o",22);
DEFINE ("LP5o",55);
DEFINE ("LP6o",66);

//LANGUAGES
DEFINE ("LANGUAGE_ENGLISH",1);
DEFINE ("LANGUAGE_GERMAN",2);
DEFINE ("LANGUAGE_FRENCH",3);

//PLOTTYPES
DEFINE("PLOT_TYPE_Y1_AXIS",1);
DEFINE("PLOT_TYPE_Y2_AXIS",2);
DEFINE("PLOT_TYPE_XY_AXIS",3);
DEFINE("PLOT_TYPE_HISTOGRAM",4);
DEFINE("PLOT_TYPE_N_PLOTS",5);

//AXIS
DEFINE("AXE_X",1);
DEFINE("AXE_Y1",2);
DEFINE("AXE_Y2",3);
DEFINE("AXE_Z",4);
