<table id="dtb_listitems" class="dTable table table-hover table-bordered">
	<thead>
		<tr>
            <th>Item</th>
            <th>Qty.</th>
            <th>Unit Price</th>
            <th>Amount</th>
            <th>Item Code</th>
            <th>Manage</th>
		</tr>
	</thead>
	<tbody>
    </tbody>
</table>

<script type="text/javascript">
<!--
$(function (){
	var dtb_listitems = $('#dtb_listitems').dataTable( {
		"sDom": "<'row-fluid'<'span6'T><'span6'f>r>t<'row-fluid'<'span6'i><'span6'pl>>",
		"sPaginationType": "bootstrap",
	    "iDisplayLength" : 10,
		"bAutoWidth": false,
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "/liststoresource",
		"sServerMethod": "POST",
		"bStateSave": false,
	    "sScrollY": "350px",
	    "bPaginate": false,

		"oLanguage" : {
			 "sUrl" : "/js/locale/datatables.english.txt"
		    },

		"aoColumnDefs": [
			                 { "bSortable": false, "aTargets": [ 4, 5 ] }
			             ],

		"oTableTools": {
			"sRowSelect": "single",
			"sSwfPath": "/js/tabletools/swf/copy_csv_xls_pdf.swf",
			"aButtons": [
							"copy",
							"print",
							"xls",
							"pdf",
							{
			                    "sExtends":    "text",
			                    "sButtonText" : "New Store Item",
			                    "sButtonClass" : "",
			                    "fnClick": function ( nButton, oConfig, oFlash ) {
			                        $.post('/updatestore',
			                        	{
			                               send : false,
			                        	},
			                        	function (data){
			                        	    $('#liststoreitems').html(data);
			                        	});
			                    }
			                }]
		}
	});

	$(".table").tablecloth({ theme: "paper" });

});
//-->
</script>