<legend>Stores: <?php echo $this->state; ?></legend>
<?php echo $this->form; ?>

<script type="text/javascript">
<!--
$(function(){

	$('#frm_storeitems').ajaxForm({
		//options of ajaxForm

		url : '/updatestore',
		data : {
			send : '<?php echo $this->sendState; ?>',
    		}, //data to be submitted along with the form variables json formatted
		clearForm : null, // form to be cleared if submit is successfull,

		dataType : 'json',  // json, xml, or script
		type : 'POST', // type of ajax call GET or POST

 		beforeSubmit : function (arr, $form, options){
		    if($('#isValid').val() == "false")
    		    return false;
		},

		success: function (data){
			$('a[href="#liststoreitems"]').click();
        }

    });

	ValidateAjax.initialize("frm_storeitems", "/validateform");

});
//-->
</script>