<?php echo $this->labels; ?>
<label id="clt" style="display: none;"></label>

<div class="row-fluid"></div>
	<div class="row-fluid">
	<div class="span4" id="user-list">
							<h4 class="heading">Students' Attendance <small></small></h4>
							<div class="row-fluid">
								<div class="input-prepend">
									<span class="add-on ad-on-icon"><i class="icon-user"></i></span><input type="text" class="user-list-search search" placeholder="Search user" />
								</div>
								<ul class="nav nav-pills line_sep">
									<li class="dropdown">
										<a class="dropdown-toggle" data-toggle="dropdown" href="#">Sort by <b class="caret"></b></a>
										<ul class="dropdown-menu sort-by">
											<li><a href="javascript:void(0)" class="sort" data-sort="sl_name">by name</a></li>
											<li><a href="javascript:void(0)" class="sort" data-sort="sl_status">by status</a></li>
										</ul>
									</li>
									<li class="dropdown">
										<a class="dropdown-toggle" data-toggle="dropdown" href="#">Show <b class="caret"></b></a>
										<ul class="dropdown-menu filter">
											<li class="active"><a href="javascript:void(0)" id="filter-none">All</a></li>
											<li><a href="javascript:void(0)" id="filter-present">Present</a></li>
											<li><a href="javascript:void(0)" id="filter-absent">Absent</a></li>
										</ul>
									</li>
									<li><select class="pull-right" id="gradelevel" onchange="$.fn.StudentsInClass($('#gradelevel option:selected').val());" style="margin-left:15%; margin-bottom: 0px; padding: 2px 6px; height: 25px; width:100%" >
											<?php foreach ($this->classes as $grade) { ?>
												<option value="<?php echo $grade?>"><?php echo $this->getGradeName($grade)?></option>
											<?php } ?>
										</select>
									</li>
								</ul>
							</div>
							<ul class="list user_list" id="studentslist">
								<?php foreach ($this->students as $student) { ?>
									<li>
									   <a href="#"><?php $sid = $student['cl_GPSN_ID']; echo ($student['present'])? "<span class='label label-success pull-right sl_status'>present</span>":
									    		"<span class='label label-important pull-right sl_status' id='$sid' onclick='$.fn.bookAttendance($sid);'>absent</span>"?></a>
										<a href="#" class="sl_name" onclick="$.fn.loadClassTeacherComment(<?php echo $student['cl_GPSN_ID']?>,'<?php echo $student['fullname']?>');"><?php echo $student['fullname']?></a><br />
										<small class="s_color sl_email"><?php echo $student['cl_GPSN_ID']?><span class="label label-info pull-left"><?php echo $s = "Total attendance: ". $student['totalattendance']." out of ".round($this->schooldays);?></span></small>
									</li>
								<?php } ?>
							</ul>
							<div class="pagination"><ul class="paging bottomPaging"></ul></div>
                        </div>

		<div class="span8">
			<div class="w-box" id="w_sort07">
				<div class="w-box-header">Instructor's Dashboard <span class="label label-important" id="sstdname" style="margin-top: 4px; margin-left: 30px;" ></span></div>
				<div class="w-box-content" style="min-height: 400px;">
						<div class="tabbable clearfix">
							<ul class="nav nav-tabs">
								<li class="active"><a href="#tab1" data-toggle="tab">Class Teacher's Comment</a></li>
								<li><a href="#tab2" data-toggle="tab">Performance Notifications</a></li>
<!-- 								<li><a href="#tab3" data-toggle="tab">School Calendar</a></li> -->
<!-- 								<li><a href="#tab4" data-toggle="tab">Online News</a></li> -->
							</ul>
							<div class="tab-content">
							<div class="tab-pane active" id="tab1">
								<div class="page-toolbar clearfix">
										<div class="btn-group pull-left">
											<a href="javascript:void(0)" class="btn btn-small toolbar-icon" onclick="javascript:$('#classteacher').val('');"><i class="icon-remove"></i></a>
<!-- 											<a href="javascript:void(0)" class="btn btn-small toolbar-icon"><i class="icon-print"></i></a>  -->
											<a href="javascript:void(0)" onclick="$.fn.loadClassTeacherComment($('#std').text(),$('#sstdname').text());" class="btn btn-small toolbar-icon"><i class="icon-refresh"></i></a>
											<a href="javascript:void(0)" id="btn_edit"  onclick="$.fn.updateClassTeacherComment();" class="btn btn-small toolbar-icon"><i class="splashy-check"></i></a>

										<?php if (Zend_Auth::getInstance()->hasIdentity()){ if (Zend_Auth::getInstance()->getIdentity()->role == 100) {?>
											<a class="btn btn-small" onclick="$.fn.printStatement();"><i class="icon-print"></i> Statement of Accounts (PDF)</a>
										<?php }} ?>
										</div>
										<span id="std" style="margin-top : 4px; display: none;"></span>
										<div class="btn-group pull-right">
											<a href="javascript:void(0)" onclick="$('a[href=\'#tab2\']').click();" class="btn btn-small toolbar-icon"><i class="icon-chevron-right"></i></a>
										</div>
								</div>
								<textarea id="classteacher" style="resize:none; width:98%; height : 100px;" readonly="readonly"><?php echo $this->cleanString("Select a student from the list on the left to display class teacher's comment") ?>
								</textarea>

								<div class="formSep" style="padding-bottom:20px;"></div>
								<h4 class="heading" style="font-size: 16px; ">Welcome to your new dashboard</h4>
								<div class="clearfix">
									<blockquote>
										<p>A strong and robust platform that makes the job of school administration efficient and effective.</p>
										<small>www.greports.com</small>
									</blockquote>
									<div class="span4">
										<?php if ($this->useCambridge) { ?>
											<img style="margin-bottom: 0px;" class="img-polaroid" src="/img/camlogo.png" alt="" width="200" />
										<?php } ?>
										<dl>
											<dd>Student Population : <strong><?php echo $this->studentno;?></strong></dd>
											<?php if (isset($this->axCount)) {?>
											<dd>
												<abbr title="Total Class Assessments in Term <?php echo $this->term;?> of <?php echo $this->year;?>">TCAS :</abbr>
												{<?php echo $this->term;?>/<?php echo $this->year ?>} : <strong><?php echo $this->axCount?></strong>
											</dd>
											<dd><abbr title="Average Assignment Per Student">AAPStudent</abbr> : <?php echo number_format(($this->axCount/$this->studentno),2);?>
											<?php } ?>
										</dl>
									</div>
									<div class="span3">
										<address style="margin-bottom: 0px">
											<strong>Support:</strong><br>
											<abbr title="Phone">P:</abbr> (+233)-024-346-3320 <br>
											<abbr title="Phone">P:</abbr> (+233)-024-635-9711 <br>
											<abbr title="Email">E:</abbr> <a href="mailto:info@greports.com">info@greports.com</a><br>
											<abbr title="Email">E:</abbr> <a href="mailto:info@greports.com">support@greports.com</a><br>
										</address>
									</div>
									<div class="span4">
										<h2 style="color : rgba(153, 101, 21,0.5); font-size: 80px; margin-top: 2px; margin-bottom: 3px; margin-left: 20px;">
										<sup style="font-size: 70px"><?php echo $this->currentweek; ?></sup>/<?php echo $this->totalweeks?><br><small class="label label-success" style="font-size:12px; font-weight: bold;"><?php echo date('d/M/Y',$this->sd)?> - <?php echo date('d/M/Y',$this->ed)?></small></h2>
									</div>
								</div>
							</div>
							<div class="tab-pane" id="tab2"  >
										<div class="page-toolbar clearfix">
											<div class="btn-group pull-right">
												<a href="javascript:void(0)" onclick="$('a[href=\'#tab1\']').click();" class="btn btn-small toolbar-icon"><i class="icon-chevron-left"></i></a>
											</div>
										</div>

								<div style="width: 99%">
									<h3 class="heading">Student Performance Notifications</h3>
									<div class="row-fluid">
										<div class="span12">
											<div class="vcard">
												<img id="picture" class="thumbnail" src="http://www.placehold.it/80x80/EFEFEF/AAAAAA" alt="Picture" width="80"/>
												<ul>
													<li class="v-heading">
														Recent Activity Information
													</li>
													<li id='recent'>

													</li>
												</ul>
											</div>
										</div>
									</div>
									</div>
							</div>
							<div class="tab-pane" id="tab3">
								<div class="span12">
									<h4 class="heading">Google Calendar (US Holidays)</h4>
									<div id="calendar_google"></div>
								</div>
							</div>
							<div class="tab-pane" id="tab4">
							 <div class="span6">
						 	 </div>
						  </div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>

<script type="text/javascript">
<!--
$(function(){
	//* filterable list
	gebo_flist.init();

	$.fn.updateClassTeacherComment = function (){
		if ($('#classteacher').prop('readonly') != true){
			$.post(
					'/loadclasscomments',
					{
						update : 1,
						studentid : $('#std').text(),
						grade : $('#g').text(),
						comment : $('#classteacher').val()
					},
					function (response){
						$.showMessage('Comment successfully updated','success');
					});
		}else{
			$.showMessage('Operation not allowed - Access level violations','error');
		};
	};

	$.fn.loadClassTeacherComment = function(stdid, sname){
		$('#sstdname').text(sname);
		$.post(
				'/loadclasscomments',
				{
					studentid : stdid,
					grade : $('#g').text(),
				},
				function (response){
					$('#classteacher').val(response.comment);
					$("#classteacher_counter").remove();
					$("#classteacher").counter({goal:300});
					$("#classteacher_counter").addClass("pull-right");
					$('#clt').text(response.allow);
					$('#std').text(stdid);
					$('#picture').prop('src',response.picture);
				});


		$.fn.recentAssignments(stdid);
	};

	$.fn.recentAssignments = function (stdid){
		$.post(
				'/recentstudentassignments',
				{
					studentid : stdid,
				},
				function (response){
					$('#recent').html(response);

				});
	};

	$.fn.StudentsInClass = function(grade) {
		$('#g').text(grade);
		$('#std').text('');
		$('#clt').text('false');
		$('#classteacher').editable("destroy");
		$.post(
			'/studentslist',
			{
				grade : grade,
				dash : 1
			},
			function (response){
				$('#studentslist').html(response);
				gebo_flist.init();
			});
	};

	$.fn.bookAttendance = function (std){

		if (std == ''){
			$.showMessage('No student ID provided');
			return;
		}

		$.post('/bookattendance',
				{
					post : true,
					studentid : std
				},
				function (response){
					$.showMessage(response.message,'info');
					//$.fn.StudentsInClass($('#g').text());
					$('#'+std).removeClass('label-important');
					$('#'+std).addClass('label-success');
					$('#'+std).text('present');
				});
	};

	$.fn.printStatement = function(){
		$.loadModal('http://<?php echo $this->pdfhost; ?>/buildpdf?mode=<?php echo $this->mode; ?>&url=http://<?php echo $this->host; ?>/accountstatements?&tm=<?php echo $this->term?>&yr=<?php echo $this->year;?>&i=0&t=11&grade=0&cid=0','Statement of Accounts',1);
	};

	<?php if ($this->isClassTeacher) { ?>
	 if ($('#gradelevel option:selected').val() == <?php echo Zend_Auth::getInstance()->getIdentity()->cl_classteacher ?>){
		$('#classteacher').val('');
		$('#classteacher').prop('readonly','');
		$('#sstdname').text('');
		$('#btn_edit').removeClass('disabled');
	 };
	<?php }; ?>

});
gebo_flist = {
	init: function(){
		//*typeahead
		var list_source = [];
		$('.user_list li').each(function(){
			var search_name = $(this).find('.sl_name').text();
			//var search_email = $(this).find('.sl_email').text();
			list_source.push(search_name);
		});
		$('.user-list-search').typeahead({source: list_source, items:5});

		var pagingOptions = {};
		var options = {
			valueNames: [ 'sl_name', 'sl_status', 'sl_email' ],
			page: 7,
			plugins: [
				[ 'paging', {
					pagingClass	: "bottomPaging",
					innerWindow	: 1,
					left		: 1,
					right		: 1
				} ]
			]
		};
		var userList = new List('user-list', options);

		$('#filter-absent').on('click',function() {
			$('ul.filter li').removeClass('active');
			$(this).parent('li').addClass('active');
			userList.filter(function(item) {
				if (item.values().sl_status == "absent") {
					return true;
				} else {
					return false;
				}
			});
			return false;
		});
		$('#filter-present').on('click',function() {
			$('ul.filter li').removeClass('active');
			$(this).parent('li').addClass('active');
			userList.filter(function(item) {
				if (item.values().sl_status == "present") {
					return true;
				} else {
					return false;
				}
			});
			return false;
		});

		$('#filter-none').on('click',function() {
			$('ul.filter li').removeClass('active');
			$(this).parent('li').addClass('active');
			userList.filter();
			return false;
		});

		$('#user-list').on('click','.sort',function(){
				$('.sort').parent('li').removeClass('active');
				if($(this).parent('li').hasClass('active')) {
					$(this).parent('li').removeClass('active');
				} else {
					$(this).parent('li').addClass('active');
				}
			}
		);
	};
};
//-->
</script>