<div class="root">
	<header id="dss" class="h1 sticky-enabled no-topbar">
		<section class="main-header">
			<p class="title">
				<a href="./"><img src="/img/greport_logo.png" alt="greports"
					width="219" height="35"></a> <span>School Administration Made
					Easier</span>
			</p>
			<nav class="social">
				<ul>
					<li><a href="#" class="facebook">Facebook</a></li>
					<li><a href="#" class="twitter">Twitter</a></li>
					<li><a href="#" class="googleplus">Google+</a></li>
					<li><a href="#" class="pinterest">Pinterest</a></li>
					<li><a href="#" class="rss">RSS</a></li>
				</ul>
			</nav>
			<nav class="mainmenu">
				<ul>
					<li class="current-menu-item"><a href="./">Home</a></li>
					<li><a href="#">Our Services</a></li>
					<li><a href="#">Contact us</a></li>
				</ul>
			</nav>

			<div class="clear"></div>
		</section>
	</header>
	<section class="slider9 p05">
		<div class="slider">
			<article>
				<div>
					<div>
						<span class="img-border"><img src="images/temp/93.jpg" alt=""></span>
					</div>
				</div>
				<h3>Fast, Secured and Error-free Reports</h3>
				<p style="text-align: justify;">A reporting system that manages the
					entire workflow from students assignments through examinations in
					order to seemlessly enable your school/institution fast-track
					academic reports generation.</p>
				<p>
					<a href="#" class="button">Read more</a>
					<!--  <span class="more"><a
						href="#">Learn more</a></span> -->
				</p>
			</article>
			<article>
				<div>
					<div>
						<span class="img-border"><img src="images/temp/93-3.jpg" alt=""></span>
					</div>
				</div>
				<h3>Reduce your carbon footprint</h3>
				<p style="text-align: justify;">By moving your school/institutions
					academic and financial activities onto our platforms, we guarantee
					that your institution would experience significant cost savings on
					paper and its related consumables.</p>
				<p>
					<a href="#" class="button">Read more</a>
					<!-- <span class="more"><a
						href="#">Learn more</a></span> -->
				</p>
			</article>
			<article>
				<div>
					<div>
						<span class="img-border"><img src="images/temp/93-1.png" alt=""></span>
					</div>
				</div>
				<h3>Track student performance in real-time</h3>
				<p style="text-align: justify;">Stealth algorithms that monitor the
					academic performance of students, and sends notification and alerts
					to both parents and school administrators when a students
					performance seems out of pattern and in adverse position</p>
				<p>
					<a href="#" class="button">Read more</a>
					<!-- <span class="more"><a
						href="#">Learn more</a></span> -->
				</p>
			</article>
			<article>
				<div>
					<div>
						<span class="img-border"><img src="images/temp/93-4.png" alt=""></span>
					</div>
				</div>
				<h3>Financial Oversight Improved</h3>
				<p style="text-align: justify;">Effortless tracking of student fees
					and bills coupled with an automated billing of student accounts
					when billing periods are due. We also provide you an expenses
					tracking solution to regulate and monitor expenditure in your
					institution/school</p>
				<p>
					<a href="#" class="button">Read more</a>
				</p>
			</article>
			<article>
				<div>
					<div>
						<span class="img-border"><img src="images/temp/93-5.jpg" alt=""></span>
					</div>
				</div>
				<h3>Online & SMS Reporting</h3>
				<p style="text-align: justify;">Publish your termly or sessional results via our online portal or
					bulk SMS system to your students or their parents. The process from
					aggregation of students scores to the publishing of results is a
					transparent process to improve efficiency.</p>
				<p>
					<a href="#" class="button">Read More</a>
				</p>
			</article>
		</div>
		<ul class="slider-titles">
			<li><a href="#">School Academics Reporting</a></li>
			<li><a href="#">Eco-friendly</a></li>
			<li><a href="#">Performance Analytics</a></li>
			<li><a href="#">School Accounting</a></li>
			<li><a href="#">Online & SMS Reporting</a></li>
		</ul>
	</section>

	<section class="content">
		<blockquote class="quote">
			<p>Our platform has been painstakingly researched and developed over
				a period of 2years.</p>
			<p class="signature">
				- <span>Development Team</span> / greports.com
			</p>
		</blockquote>
		<!--
	<section class="span12">
		<article class="span6">
			<a href="#"><img src="/images/temp/07.jpg" alt=""
				class="post-thumbnail"></a>
			<h2>
				<a href="#">Most customizable theme ever has released</a>
			</h2>
			<p>Thanks to MultiPurpose you can now build websites with the lowest
				cost possible. MultiPurpose's goal is to help you build unique and
				modern websites fast, easy and with the lowest cost possible. With
				MultiPurpose you can create many unique style websites for
				differends needs and purposes. You can now start to build better
				websites with MultiPurpose.</p>
			<p class="more">
				<a href="#">Read more</a>
			</p>
		</article>
		<article class="span6">
			<a href="#"><img src="/images/temp/08.jpg" alt=""
				class="post-thumbnail"></a>
			<h2>
				<a href="#">Build better websites with MultiPurpose</a>
			</h2>
			<p>Most customizable responsive HTML5 and CSS3 template ever has
				released. To build your website you can choose from variety of
				headers, titles, menus, sliders, color skins, fonts, frames or
				patterns for boxed version. MultiPurpose can be used to create
				literally any type of website. The only limit is your imagination.
				Order MultiPurpose Today!</p>
			<p class="more">
				<a href="#">Read more</a>
			</p>
		</article>
	</section>

	<section class="span12">
		<div class="span8 tabbed">
			<ul class="nav nav-tabs">
				<li><a href="#art1" data-toggle="tab">Colors</a></li>
				<li><a href="#art2" data-toggle="tab">Menus</a></li>
				<li><a href="#art3" data-toggle="tab">Titles</a></li>
			</ul>
			<div class="tab-content">
			<article id="art1" class="tab-pane">
				<div class="alignleft">
					<a href="#"><img src="/images/temp/09.jpg" alt=""></a>
				</div>
				<h2>
					<a href="#">Most Customizable Ever</a>
				</h2>
				<p>We tested it and, so far there are no themes which have have, so
					much customization option included. If you find the feature that
					could help for better customization - we will inlude it in next
					release, 100% free. We are constantly working to improve the theme
					with new features according to customers feedback, so feel free to
					contact us if you need some more useful features or subpages!</p>
				<p class="more">
					<a href="#">Read more</a>
				</p>
			</article>
			<article id="art2" class="tab-pane">
				<div class="alignleft">
					<a href="#"><img src="/images/temp/10.jpg" alt=""></a>
				</div>
				<h2>
					<a href="#">14 Modern Menus</a>
				</h2>
				<p>With MultiPurpose you can build websites with the lowest cost
					possible. MultiPurpose's goal is to help you build unique and
					modern websites fast, easy and with the lowest cost possible. With
					MultiPurpose you can create many unique style websites for
					differends needs and purposes, so that you can build better
					websites with MultiPurpose now.</p>
				<p class="more">
					<a href="#">Read more</a>
				</p>
			</article>
			<article id="art3" class="tab-pane">
				<div class="alignleft">
					<a href="#"><img src="/images/temp/11.jpg" alt=""></a>
				</div>
				<h2>
					<a href="#">10 Styles of Titles</a>
				</h2>
				<p>MultiPurpose has got tons of the outstanding features. It is
					probably the most complete and custmomizable template in the world.
					It includes for example: 14 predefinied different index pages for
					multipurpose usage, 12 predefinied different menus, 12 predefinied
					different ThemeMotive sliders, 10 styles of the headlines and so
					much more.</p>
				<p class="more">
					<a href="#">Read more</a>
				</p>
			</article>
			</div>
		</div>
		<div class="span4 why-us">
			<h2>
				<span>Why MultiPurpose?</span>
			</h2>
			<ul>
				<li>Ultra customizable website template</li>
				<li>Smooth responsive design</li>
				<li>Retina ready template</li>
				<li>Unlimited color possibility</li>
				<li>Premium sliders included in the price</li>
				<li>And so much much more...</li>
			</ul>
		</div>
</section> -->
		<a href="#top" class="go-top">Go to top of page</a>
	</section>