<div class="widget widget-heading-simple widget-body-simple">
				<div class="widget-body">

					<div class="widget widget-tabs widget-tabs-icons-only-2 widget-activity margin-none widget-tabs-gray">

						<!-- Tabs Heading -->
						<div class="widget-head">
							<ul>
								<li class="active"><a class="glyphicons user_add" data-toggle="tab" href="#filterUsersTab"><i></i>Users</a></li>
								<li><a class="glyphicons shopping_cart" data-toggle="tab" href="#filterOrdersTab"><i></i>Orders</a></li>
								<li class=""><a class="glyphicons envelope" data-toggle="tab" href="#filterMessagesTab"><i></i></a></li>
								<li class=""><a class="glyphicons link" data-toggle="tab" href="#filterLinksTab"><i></i></a></li>
								<li class=""><a class="glyphicons camera" data-toggle="tab" href="#filterPhotosTab"><i></i></a></li>
							</ul>
						</div>
						<!-- // Tabs Heading END -->

						<div class="widget-body">
							<div class="tab-content">


								<!-- Filter Users Tab -->
								<div class="tab-pane active" id="filterUsersTab">
									<ul class="list">

																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon user_add"><i></i></span>
											<span class="ellipsis"><a href="">Darius Jackson</a> registered at <a href="">Darius Jackson's</a> suggestion.</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon user_add"><i></i></span>
											<span class="ellipsis"><a href="">Martin Glades</a> registered at <a href="">John Doe's</a> suggestion.</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon user_add"><i></i></span>
											<span class="ellipsis"><a href="">Jane Doe</a> registered at <a href="">Jane Doe's</a> suggestion.</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon user_add"><i></i></span>
											<span class="ellipsis"><a href="">Melisa Ragae</a> registered at <a href="">Martin Glades's</a> suggestion.</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon user_add"><i></i></span>
											<span class="ellipsis"><a href="">Martin Glades</a> registered at <a href="">John Doe's</a> suggestion.</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->

									</ul>
								</div>
								<!-- // Filter Users Tab END -->

								<!-- Filter Orders Tab -->
								<div class="tab-pane" id="filterOrdersTab">
									<ul class="list">

																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon shopping_cart"><i></i></span>
											<span class="ellipsis"><a href="">Jane Doe</a> bought 10 items worth of €50 (<a href="">order #2301</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon shopping_cart"><i></i></span>
											<span class="ellipsis"><a href="">Darius Jackson</a> bought 10 items worth of €50 (<a href="">order #2302</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon shopping_cart"><i></i></span>
											<span class="ellipsis"><a href="">John Doe</a> bought 10 items worth of €50 (<a href="">order #2303</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon shopping_cart"><i></i></span>
											<span class="ellipsis"><a href="">Jane Doe</a> bought 10 items worth of €50 (<a href="">order #2304</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon shopping_cart"><i></i></span>
											<span class="ellipsis"><a href="">John Doe</a> bought 10 items worth of €50 (<a href="">order #2305</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->

									</ul>
								</div>
								<!-- // Filter Orders Tab END -->

								<!-- Filter Messages Tab -->
								<div class="tab-pane" id="filterMessagesTab">
									<ul class="list">

																														<!-- Activity item -->
										<li class="double">
											<span class="glyphicons activity-icon envelope"><i></i></span>
											<span class="ellipsis">
												You have received an email from <a href="">Martin Glades</a> (martin.glades@wee-email.com)
												<span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
											</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																														<!-- Activity item -->
										<li class="double highlight">
											<span class="glyphicons activity-icon envelope"><i></i></span>
											<span class="ellipsis">
												You have received an email from <a href="">Martin Glades</a> (martin.glades@wee-email.com)
												<span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
											</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																														<!-- Activity item -->
										<li class="double highlight">
											<span class="glyphicons activity-icon envelope"><i></i></span>
											<span class="ellipsis">
												You have received an email from <a href="">Darius Jackson</a> (darius.jackson@fake-email.net)
												<span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
											</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																														<!-- Activity item -->
										<li class="double">
											<span class="glyphicons activity-icon envelope"><i></i></span>
											<span class="ellipsis">
												You have received an email from <a href="">Darius Jackson</a> (darius.jackson@fake-email.net)
												<span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
											</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																														<!-- Activity item -->
										<li class="double">
											<span class="glyphicons activity-icon envelope"><i></i></span>
											<span class="ellipsis">
												You have received an email from <a href="">Darius Jackson</a> (darius.jackson@fake-email.net)
												<span class="meta">on 29 March, 2013 <span>1 hour ago</span></span>
											</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->

									</ul>
								</div>
								<!-- // Filter Messages Tab END -->

								<!-- Filter Links Tab -->
								<div class="tab-pane" id="filterLinksTab">
									<ul class="list">

																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon link"><i></i></span>
											<span class="ellipsis"><a href="">Darius Jackson</a> bought 10 items worth of €50 (<a href="">order #2301</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon link"><i></i></span>
											<span class="ellipsis"><a href="">Melisa Ragae</a> bought 10 items worth of €50 (<a href="">order #2302</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon link"><i></i></span>
											<span class="ellipsis"><a href="">Martin Glades</a> bought 10 items worth of €50 (<a href="">order #2303</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon link"><i></i></span>
											<span class="ellipsis"><a href="">Melisa Ragae</a> bought 10 items worth of €50 (<a href="">order #2304</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon link"><i></i></span>
											<span class="ellipsis"><a href="">Melisa Ragae</a> bought 10 items worth of €50 (<a href="">order #2305</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->

									</ul>
								</div>
								<!-- // Filter Links Tab END -->

								<!-- Filter Photos Tab -->
								<div class="tab-pane" id="filterPhotosTab">
									<ul class="list">

																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon camera"><i></i></span>
											<span class="ellipsis"><a href="">John Doe</a> bought 10 items worth of €50 (<a href="">order #2301</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon camera"><i></i></span>
											<span class="ellipsis"><a href="">Darius Jackson</a> bought 10 items worth of €50 (<a href="">order #2302</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon camera"><i></i></span>
											<span class="ellipsis"><a href="">Jane Doe</a> bought 10 items worth of €50 (<a href="">order #2303</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->
																				<!-- Activity item -->
										<li>
											<span class="date">21/03</span>
											<span class="glyphicons activity-icon camera"><i></i></span>
											<span class="ellipsis"><a href="">John Doe</a> bought 10 items worth of €50 (<a href="">order #2304</a>)</span>
											<div class="clearfix"></div>
										</li>
										<!-- // Activity item END -->

									</ul>
								</div>
								<!-- // Filter Photos Tab END -->

							</div>
						</div>
					</div>

				</div>
			</div>
<!-- Widget -->
<div
	class="widget widget-heading-simple widget-body-gray widget-employees">
	<div class="widget-body padding-none"
		style="background-color: rgba(0, 0, 0, 0.02);
	background-image: url(/img/bgnoise.png);">
		<div class="row-fluid row-merge" style="height: 400px;">
			<div class="span4 listWrapper">
				<div class="innerAll">
					<form autocomplete="off" class="form-inline">
						<div class="widget-search separator bottom">
							<button type="button" class="btn btn-default pull-right">
								<i class="icon-search"></i>
							</button>
							<div class="overflow-hidden">
								<input type="text" value="" placeholder="Find someone ..">
							</div>
						</div>
						<select style="width: 100%;">
							<optgroup label="Department">
								<option value="design">Design</option>
								<option value="development">Development</option>
							</optgroup>
						</select>
					</form>
				</div>
				<span class="results">1490 Students Found <i
					class="icon-circle-arrow-down"></i></span>
				<ul class="list unstyled">
					<li class="active"
						style="border-bottom: 1px dashed rgb(221, 221, 221);
							border-top: 1px dashed rgb(221, 221, 221);">
						<div class="media innerAll" style="padding: 5px; ">
							<div class="media-object pull-left thumb hidden-phone">
								<img class="img-polaroid" src="http://placehold.it/25x25/00000"
									alt="Image" />
							</div>
							<div class="media-body">
								<span class="strong">Adrian Demian</span><span class="muted">contact@mosaicpro.biz</span>
 							</div>
						</div>
					</li>
					 <li style="border-bottom: 1px dashed rgb(221, 221, 221);
							border-top: 1px dashed rgb(221, 221, 221);">
						<div class="media innerAll" style="padding: 5px; ">
							<div class="media-object pull-left thumb hidden-phone">
								<img class="img-polaroid" src="http://placehold.it/25x25/00000"
									alt="Image" />
							</div>
							<div class="media-body">
								<span class="strong">Adrian Demian</span><span class="muted">contact@mosaicpro.biz</span>
 							</div>
						</div>
					</li>
					 <li style="border-bottom: 1px dashed rgb(221, 221, 221);
							border-top: 1px dashed rgb(221, 221, 221);">
						<div class="media innerAll" style="padding: 5px;">
							<div class="media-object pull-left thumb hidden-phone">
								<img class="img-polaroid" src="http://placehold.it/25x25/00000"
									alt="Image" />
							</div>
							<div class="media-body">
								<span class="strong">Adrian Demian</span><span class="muted">contact@mosaicpro.biz</span>
 							</div>
						</div>
					</li>
					 <li style="border-bottom: 1px dashed rgb(221, 221, 221);
							border-top: 1px dashed rgb(221, 221, 221);">
						<div class="media innerAll" style="padding: 5px; ">
							<div class="media-object pull-left thumb hidden-phone">
								<img class="img-polaroid" src="http://placehold.it/25x25/00000"
									alt="Image" />
							</div>
							<div class="media-body">
								<span class="strong">Adrian Demian</span><span class="muted">contact@mosaicpro.biz</span>
 							</div>
						</div>
					</li>
					 <li style="border-bottom: 1px dashed rgb(221, 221, 221);
							border-top: 1px dashed rgb(221, 221, 221);">
						<div class="media innerAll" style="padding: 5px; ">
							<div class="media-object pull-left thumb hidden-phone">
								<img class="img-polaroid" src="http://placehold.it/25x25/00000"
									alt="Image" />
							</div>
							<div class="media-body">
								<span class="strong">Adrian Demian</span><span class="muted">contact@mosaicpro.biz</span>
 							</div>
						</div>
					</li>
					 <li style="border-bottom: 1px dashed rgb(221, 221, 221);
							border-top: 1px dashed rgb(221, 221, 221);">
						<div class="media innerAll" style="padding: 5px; ">
							<div class="media-object pull-left thumb hidden-phone">
								<img class="img-polaroid" src="http://placehold.it/25x25/00000"
									alt="Image" />
							</div>
							<div class="media-body">
								<span class="strong">Adrian Demian</span><span class="muted">contact@mosaicpro.biz</span>
 							</div>
						</div>
					</li>
					 <li style="border-bottom: 1px dashed rgb(221, 221, 221);
							border-top: 1px dashed rgb(221, 221, 221);">
						<div class="media innerAll" style="padding: 5px; ">
							<div class="media-object pull-left thumb hidden-phone">
								<img class="img-polaroid" src="http://placehold.it/25x25/00000"
									alt="Image" />
							</div>
							<div class="media-body">
								<span class="strong">Adrian Demian</span><span class="muted">contact@mosaicpro.biz</span>
 							</div>
						</div>
					</li>

				</ul>
			</div>
			<div class="span8 detailsWrapper">
				<div class="ajax-loading hide">
					<i class="icon-spinner icon-spin icon-4x"></i>
				</div>
				<div class="innerAll">
					<div class="title">
						<div class="row-fluid">
							<div class="span8">
								<h3 class="text-primary">Adrian Demian</h3>
								<span class="muted">Senior Designer</span>
							</div>

						</div>
					</div>
					<hr />
					<div class="body">
						<div class="row-fluid">
							<div class="span4 overflow-hidden">
								<!-- Profile Photo -->
								<div class="center">
									<a href="" class="thumb inline-block"><img class="img-polaroid"
										src="http://placehold.it/300x200" alt="Profile" /></a>
								</div>
								<div class="separator bottom"></div>
								<!-- // Profile Photo END -->
								<ul class="icons-ul" style="list-style: none;">
									<li><i class="icon-envelope icon-li icon-fixed-width"></i>
										contac@mosaicpro.biz</li>
									<li><i class="icon-phone icon-li icon-fixed-width"></i> 00353
										9191238101</li>
									<li><i class="icon-skype icon-li icon-fixed-width"></i>
										mosaicpro</li>
								</ul>
							</div>
							<div class="span8">
								<h5 class="strong">About</h5>
								<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed
									diam nonummy nibh euismod tincidunt ut laoreet dolore magna
									aliquam erat volutpat.</p>
								<div class="row-fluid">
									<div class="span12">
										<h5 class="strong">Reports</h5>
										<a href="" class="btn btn-primary btn-small"><i
											class="icon-download-alt icon-fixed-width"></i> June</a> <a
											href="" class="btn btn-default btn-small"><i
											class="icon-download-alt icon-fixed-width"></i> May</a> <a
											href="" class="btn btn-default btn-small "><i
											class="icon-download-alt icon-fixed-width"></i> April</a>
										<div class="separator bottom"></div>
									</div>

								</div>
								<h5 class="text-uppercase strong text-primary">
									<i class="icon-group text-regular icon-fixed-width"></i>
									MosaicPro <span class="text-lowercase strong padding-none">Team</span>
									<span class="text-lowercase padding-none">(2 people)</span>
								</h5>
								<ul class="team">
									<li><span class="crt">1</span><span class="strong">Adrian
											Demian</span><span class="muted">Senior Designer</span></li>
									<li><span class="crt">2</span><span class="strong">Laza Bogdan</span><span
										class="muted">Senior Developer</span></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
<!-- // Widget END -->