       <!-- sample modal content -->
          <div id="myModal" class="modal hide fade rModal"tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h3 id="myModalLabel">Modal Heading</h3>
            </div>

            <div class="modal-body" id="mm">

            </div>
            <div class="modal-footer">
              <button class="btn" data-dismiss="modal">Close</button>
              <button class="btn btn-primary">Save changes</button>
            </div>
          </div>

         <a data-toggle="modal" data-remote="/buildpdf?url=http://www.casensuits.com/<?php echo $this->printURL; ?>" data-target="#myModal" class="btn btn-primary btn-mini">Launch demo modal</a>
